"""baseline

Revision ID: 99b27bca3441
Revises: 
Create Date: 2026-02-26 09:50:07.892281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('consent_templates',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('signature_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('general','surgery','sedation','orthodontics','implants','endodontics','pediatric')", name='chk_consent_templates_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consent_templates_category', 'consent_templates', ['category'], unique=False)
    op.create_table('evolution_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('procedure_type', sa.String(length=50), nullable=False),
    sa.Column('cups_code', sa.String(length=10), nullable=True),
    sa.Column('complexity', sa.String(length=20), server_default='simple', nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("complexity IN ('simple', 'moderate', 'complex')", name='chk_evolution_templates_complexity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evolution_templates_is_active', 'evolution_templates', ['is_active'], unique=False)
    op.create_index('idx_evolution_templates_procedure_type', 'evolution_templates', ['procedure_type'], unique=False)
    op.create_table('reminder_configs',
    sa.Column('reminders', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('default_channels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["sms"]\'::jsonb'), nullable=False),
    sa.Column('max_reminders_allowed', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_catalog',
    sa.Column('cups_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('default_price', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('diagnostic','preventive','restorative','endodontic','periodontic','surgical','orthodontic','prosthodontic','other')", name='chk_service_catalog_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cups_code', name='uq_service_catalog_cups_code')
    )
    op.create_index('idx_service_catalog_category', 'service_catalog', ['category'], unique=False)
    op.create_index('idx_service_catalog_cups_code', 'service_catalog', ['cups_code'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('professional_license', sa.String(length=50), nullable=True),
    sa.Column('specialties', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('clinic_owner', 'doctor', 'assistant', 'receptionist')", name='chk_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email_lower', 'users', [sa.text('lower(email)')], unique=True)
    op.create_table('availability_blocks',
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('vacation', 'conference', 'personal', 'sick_leave', 'training', 'other')", name='chk_availability_blocks_reason'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_availability_blocks_doctor_time', 'availability_blocks', ['doctor_id', 'start_time', 'end_time'], unique=False)
    op.create_table('digital_signatures',
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('signer_type', sa.String(length=20), nullable=False),
    sa.Column('signer_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('canonical_payload', sa.Text(), nullable=False),
    sa.Column('signature_hash', sa.String(length=64), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('consent','treatment_plan','quotation','prescription')", name='chk_digital_signatures_doc_type'),
    sa.CheckConstraint("signer_type IN ('patient','doctor','clinic_owner','witness')", name='chk_digital_signatures_signer_type'),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type', 'document_id', 'signer_type', name='uq_digital_signatures_doc_signer')
    )
    op.create_index('idx_digital_signatures_document', 'digital_signatures', ['document_type', 'document_id'], unique=False)
    op.create_index('idx_digital_signatures_signer', 'digital_signatures', ['signer_id'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('breaks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('appointment_duration_defaults', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"consultation": 30, "procedure": 60, "emergency": 30, "follow_up": 20}\'::jsonb'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='chk_doctor_schedules_day_of_week'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day_of_week', name='uq_doctor_schedules_user_day')
    )
    op.create_index('idx_doctor_schedules_user', 'doctor_schedules', ['user_id'], unique=False)
    op.create_table('evolution_template_steps',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['evolution_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'step_order', name='uq_evolution_template_steps_order')
    )
    op.create_index('idx_evolution_template_steps_template', 'evolution_template_steps', ['template_id'], unique=False)
    op.create_table('evolution_template_variables',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('variable_type', sa.String(length=20), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("variable_type IN ('text', 'number', 'select', 'date')", name='chk_evolution_template_variables_type'),
    sa.ForeignKeyConstraint(['template_id'], ['evolution_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'name', name='uq_evolution_template_variables_name')
    )
    op.create_index('idx_evolution_template_variables_template', 'evolution_template_variables', ['template_id'], unique=False)
    op.create_table('patients',
    sa.Column('document_type', sa.String(length=10), nullable=False),
    sa.Column('document_number', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_secondary', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('insurance_provider', sa.String(length=100), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=50), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('allergies', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('chronic_conditions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('referral_source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_show_count', sa.Integer(), nullable=False),
    sa.Column('portal_access', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('CC', 'CE', 'PA', 'PEP', 'TI')", name='chk_patients_document_type'),
    sa.CheckConstraint("gender IS NULL OR gender IN ('male', 'female', 'other')", name='chk_patients_gender'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type', 'document_number', name='uq_patients_document')
    )
    op.create_index('idx_patients_created_at', 'patients', ['created_at'], unique=False)
    op.create_index('idx_patients_document', 'patients', [sa.text('lower(document_type)'), sa.text('lower(document_number)')], unique=False)
    op.create_index('idx_patients_email', 'patients', ['email'], unique=False)
    op.create_index('idx_patients_is_active', 'patients', ['is_active'], unique=False)
    op.create_table('user_invites',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('doctor', 'assistant', 'receptionist')", name='chk_invites_role'),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'expired', 'cancelled')", name='chk_invites_status'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_invites_email'), 'user_invites', ['email'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('anamnesis',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medical_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dental_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('family_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('habits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', name='uq_anamnesis_patient')
    )
    op.create_table('clinical_records',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tooth_numbers', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('edit_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('examination', 'evolution_note', 'procedure')", name='chk_clinical_records_type'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clinical_records_created_at', 'clinical_records', ['created_at'], unique=False)
    op.create_index('idx_clinical_records_doctor', 'clinical_records', ['doctor_id'], unique=False)
    op.create_index('idx_clinical_records_patient', 'clinical_records', ['patient_id'], unique=False)
    op.create_index('idx_clinical_records_type', 'clinical_records', ['type'], unique=False)
    op.create_table('consents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content_rendered', sa.Text(), nullable=False),
    sa.Column('content_snapshot', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'pending_signatures', 'signed', 'voided')", name='chk_consents_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consents_patient', 'consents', ['patient_id'], unique=False)
    op.create_index('idx_consents_status', 'consents', ['status'], unique=False)
    op.create_index('idx_consents_template', 'consents', ['template_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('cie10_code', sa.String(length=10), nullable=False),
    sa.Column('cie10_description', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tooth_number', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('mild', 'moderate', 'severe')", name='chk_diagnoses_severity'),
    sa.CheckConstraint("status IN ('active', 'resolved')", name='chk_diagnoses_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_diagnoses_cie10', 'diagnoses', ['cie10_code'], unique=False)
    op.create_index('idx_diagnoses_doctor', 'diagnoses', ['doctor_id'], unique=False)
    op.create_index('idx_diagnoses_patient', 'diagnoses', ['patient_id'], unique=False)
    op.create_index('idx_diagnoses_status', 'diagnoses', ['status'], unique=False)
    op.create_table('odontogram_conditions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('tooth_number', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('condition_code', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=10), server_default='manual', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("condition_code IN ('caries','restoration','extraction','absent','crown','endodontic','implant','fracture','sealant','fluorosis','temporary','prosthesis')", name='chk_odontogram_conditions_code'),
    sa.CheckConstraint("severity IS NULL OR severity IN ('mild', 'moderate', 'severe')", name='chk_odontogram_conditions_severity'),
    sa.CheckConstraint("source IN ('manual', 'voice')", name='chk_odontogram_conditions_source'),
    sa.CheckConstraint("zone IN ('mesial','distal','vestibular','lingual','palatino','oclusal','incisal','root','full')", name='chk_odontogram_conditions_zone'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'tooth_number', 'zone', name='uq_odontogram_conditions_tooth_zone')
    )
    op.create_index('idx_odontogram_conditions_patient', 'odontogram_conditions', ['patient_id'], unique=False)
    op.create_index('idx_odontogram_conditions_tooth', 'odontogram_conditions', ['patient_id', 'tooth_number'], unique=False)
    op.create_table('odontogram_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('tooth_number', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('condition_code', sa.String(length=30), nullable=False),
    sa.Column('previous_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_odontogram_history_created', 'odontogram_history', ['created_at'], unique=False)
    op.create_index('idx_odontogram_history_patient_tooth', 'odontogram_history', ['patient_id', 'tooth_number'], unique=False)
    op.create_table('odontogram_states',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('dentition_type', sa.String(length=20), server_default='adult', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dentition_type IN ('adult', 'pediatric', 'mixed')", name='chk_odontogram_states_dentition_type'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index('idx_odontogram_states_patient', 'odontogram_states', ['patient_id'], unique=False)
    op.create_table('patient_documents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('tooth_number', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patient_documents_patient', 'patient_documents', ['patient_id'], unique=False)
    op.create_index('idx_patient_documents_type', 'patient_documents', ['patient_id', 'document_type'], unique=False)
    op.create_table('signature_verifications',
    sa.Column('signature_id', sa.UUID(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('computed_hash', sa.String(length=64), nullable=False),
    sa.Column('stored_hash', sa.String(length=64), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signature_id'], ['digital_signatures.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signature_verifications_signature', 'signature_verifications', ['signature_id'], unique=False)
    op.create_table('tooth_photos',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('tooth_number', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_s3_key', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tooth_photos_patient', 'tooth_photos', ['patient_id'], unique=False)
    op.create_index('idx_tooth_photos_tooth', 'tooth_photos', ['patient_id', 'tooth_number'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_cost_estimated', sa.Integer(), nullable=False),
    sa.Column('total_cost_actual', sa.Integer(), nullable=False),
    sa.Column('signature_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'completed', 'cancelled')", name='chk_treatment_plans_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_treatment_plans_doctor', 'treatment_plans', ['doctor_id'], unique=False)
    op.create_index('idx_treatment_plans_patient', 'treatment_plans', ['patient_id'], unique=False)
    op.create_index('idx_treatment_plans_status', 'treatment_plans', ['status'], unique=False)
    op.create_table('voice_sessions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('context', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("context IN ('odontogram', 'evolution', 'examination')", name='chk_voice_sessions_context'),
    sa.CheckConstraint("status IN ('active', 'applied', 'expired')", name='chk_voice_sessions_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_voice_sessions_doctor', 'voice_sessions', ['doctor_id'], unique=False)
    op.create_index('idx_voice_sessions_patient', 'voice_sessions', ['patient_id'], unique=False)
    op.create_table('waitlist_entries',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('preferred_doctor_id', sa.UUID(), nullable=True),
    sa.Column('procedure_type', sa.String(length=100), nullable=True),
    sa.Column('preferred_days', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('preferred_time_from', sa.Time(), nullable=True),
    sa.Column('preferred_time_to', sa.Time(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notification_count', sa.Integer(), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('waiting', 'notified', 'scheduled', 'expired', 'cancelled')", name='chk_waitlist_entries_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['preferred_doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_waitlist_entries_patient', 'waitlist_entries', ['patient_id'], unique=False)
    op.create_index('idx_waitlist_entries_status', 'waitlist_entries', ['status'], unique=False)
    op.create_table('odontogram_snapshots',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dentition_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('linked_record_id', sa.UUID(), nullable=True),
    sa.Column('linked_treatment_plan_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['linked_record_id'], ['clinical_records.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_odontogram_snapshots_created', 'odontogram_snapshots', ['created_at'], unique=False)
    op.create_index('idx_odontogram_snapshots_patient', 'odontogram_snapshots', ['patient_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('medications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prescriptions_created_at', 'prescriptions', ['created_at'], unique=False)
    op.create_index('idx_prescriptions_doctor', 'prescriptions', ['doctor_id'], unique=False)
    op.create_index('idx_prescriptions_patient', 'prescriptions', ['patient_id'], unique=False)
    op.create_table('quotations',
    sa.Column('quotation_number', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('treatment_plan_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signature_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'sent', 'approved', 'rejected', 'expired')", name='chk_quotations_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_number', name='uq_quotations_number')
    )
    op.create_index('idx_quotations_created_at', 'quotations', ['created_at'], unique=False)
    op.create_index('idx_quotations_patient', 'quotations', ['patient_id'], unique=False)
    op.create_index('idx_quotations_status', 'quotations', ['status'], unique=False)
    op.create_table('treatment_plan_items',
    sa.Column('treatment_plan_id', sa.UUID(), nullable=False),
    sa.Column('cups_code', sa.String(length=10), nullable=False),
    sa.Column('cups_description', sa.String(length=500), nullable=False),
    sa.Column('tooth_number', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Integer(), nullable=False),
    sa.Column('actual_cost', sa.Integer(), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('procedure_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'scheduled', 'completed', 'cancelled')", name='chk_treatment_plan_items_status'),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procedure_id')
    )
    op.create_index('idx_treatment_plan_items_plan', 'treatment_plan_items', ['treatment_plan_id'], unique=False)
    op.create_index('idx_treatment_plan_items_status', 'treatment_plan_items', ['status'], unique=False)
    op.create_table('voice_parses',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('corrections', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('filtered_speech', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('llm_model', sa.String(length=50), nullable=False),
    sa.Column('llm_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'partial')", name='chk_voice_parses_status'),
    sa.ForeignKeyConstraint(['session_id'], ['voice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_voice_parses_session', 'voice_parses', ['session_id'], unique=False)
    op.create_table('voice_transcriptions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='chk_voice_transcriptions_status'),
    sa.ForeignKeyConstraint(['session_id'], ['voice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_voice_transcriptions_session', 'voice_transcriptions', ['session_id'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('treatment_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by_patient', sa.Boolean(), nullable=False),
    sa.Column('no_show_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_show')", name='chk_appointments_status'),
    sa.CheckConstraint("type IN ('consultation', 'procedure', 'emergency', 'follow_up')", name='chk_appointments_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_item_id'], ['treatment_plan_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appointments_cursor', 'appointments', ['start_time', 'id'], unique=False)
    op.create_index('idx_appointments_doctor_start_status', 'appointments', ['doctor_id', 'start_time', 'status'], unique=False)
    op.create_index('idx_appointments_patient_start', 'appointments', ['patient_id', 'start_time'], unique=False)
    op.create_index('idx_appointments_start_time', 'appointments', ['start_time'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'sent', 'partial', 'paid', 'overdue', 'cancelled')", name='chk_invoices_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number', name='uq_invoices_number')
    )
    op.create_index('idx_invoices_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index('idx_invoices_patient', 'invoices', ['patient_id'], unique=False)
    op.create_index('idx_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('procedures',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('cups_code', sa.String(length=10), nullable=False),
    sa.Column('cups_description', sa.String(length=500), nullable=False),
    sa.Column('tooth_number', sa.Integer(), nullable=True),
    sa.Column('zones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('materials_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('treatment_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('clinical_record_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinical_record_id'], ['clinical_records.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_item_id'], ['treatment_plan_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('treatment_plan_item_id')
    )
    op.create_index('idx_procedures_created_at', 'procedures', ['created_at'], unique=False)
    op.create_index('idx_procedures_cups', 'procedures', ['cups_code'], unique=False)
    op.create_index('idx_procedures_doctor', 'procedures', ['doctor_id'], unique=False)
    op.create_index('idx_procedures_patient', 'procedures', ['patient_id'], unique=False)
    op.create_table('quotation_items',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('cups_code', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('tooth_number', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quotation_items_quotation', 'quotation_items', ['quotation_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('cups_code', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('tooth_number', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoice_items_invoice', 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('payment_plans',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('num_installments', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'cancelled')", name='chk_payment_plans_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_plans_invoice', 'payment_plans', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('received_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash', 'card', 'transfer', 'other')", name='chk_payments_method'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_date', 'payments', ['payment_date'], unique=False)
    op.create_index('idx_payments_invoice', 'payments', ['invoice_id'], unique=False)
    op.create_index('idx_payments_patient', 'payments', ['patient_id'], unique=False)
    op.create_table('payment_plan_installments',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'paid', 'overdue')", name='chk_installments_status'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['payment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_installments_due_date', 'payment_plan_installments', ['due_date'], unique=False)
    op.create_index('idx_installments_plan', 'payment_plan_installments', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop all tenant tables in reverse topological order (children first)

    # Level 7
    op.drop_table('payment_plan_installments')

    # Level 6
    op.drop_table('invoice_items')
    op.drop_table('payments')
    op.drop_table('payment_plans')

    # Level 5
    op.drop_table('quotation_items')

    # Level 4
    op.drop_table('procedures')
    op.drop_table('appointments')
    op.drop_table('invoices')

    # Level 3
    op.drop_table('treatment_plan_items')
    op.drop_table('voice_parses')
    op.drop_table('voice_transcriptions')
    op.drop_table('odontogram_snapshots')
    op.drop_table('prescriptions')
    op.drop_table('quotations')

    # Level 2
    op.drop_table('waitlist_entries')
    op.drop_table('voice_sessions')
    op.drop_table('treatment_plans')
    op.drop_table('tooth_photos')
    op.drop_table('signature_verifications')
    op.drop_table('patient_documents')
    op.drop_table('odontogram_states')
    op.drop_table('odontogram_history')
    op.drop_table('odontogram_conditions')
    op.drop_table('diagnoses')
    op.drop_table('consents')
    op.drop_table('clinical_records')
    op.drop_table('anamnesis')

    # Level 1
    op.drop_table('user_sessions')
    op.drop_table('user_invites')
    op.drop_table('patients')
    op.drop_table('evolution_template_variables')
    op.drop_table('evolution_template_steps')
    op.drop_table('doctor_schedules')
    op.drop_table('digital_signatures')
    op.drop_table('availability_blocks')

    # Level 0
    op.drop_table('users')
    op.drop_table('service_catalog')
    op.drop_table('reminder_configs')
    op.drop_table('evolution_templates')
    op.drop_table('consent_templates')
    op.drop_table('audit_logs')

