#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# DentalOS — Server Setup Script (Hetzner CX31 / Ubuntu 22.04+)
#
# Idempotent — safe to run multiple times.
# Installs Docker, generates secrets, configures firewall and Nginx.
#
# Usage:
#   ssh root@your-server 'bash -s' < scripts/deploy/setup-server.sh
#   # or copy to server and run:
#   chmod +x setup-server.sh && sudo ./setup-server.sh
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

DEPLOY_DIR="/opt/dentalos"
DOMAIN="${DENTALOS_DOMAIN:-app.dentalos.co}"

echo "═══════════════════════════════════════════════════"
echo "  DentalOS — Server Setup"
echo "  Target: ${DEPLOY_DIR}"
echo "  Domain: ${DOMAIN}"
echo "═══════════════════════════════════════════════════"

# ── 1. System updates ───────────────────────────────────────────────────────
echo "[1/7] Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq

# ── 2. Install Docker CE + Compose plugin ────────────────────────────────────
if ! command -v docker &>/dev/null; then
    echo "[2/7] Installing Docker CE..."
    apt-get install -y -qq ca-certificates curl gnupg
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
        > /etc/apt/sources-list.d/docker.list
    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
    systemctl enable --now docker
else
    echo "[2/7] Docker already installed, skipping."
fi

# ── 3. Create deploy directory structure ─────────────────────────────────────
echo "[3/7] Creating directory structure..."
mkdir -p "${DEPLOY_DIR}"/{keys,backups,logs}

# ── 4. Generate JWT RSA keys (if not exists) ─────────────────────────────────
if [ ! -f "${DEPLOY_DIR}/keys/private.pem" ]; then
    echo "[4/7] Generating JWT RSA 2048-bit keys..."
    openssl genrsa -out "${DEPLOY_DIR}/keys/private.pem" 2048
    openssl rsa -in "${DEPLOY_DIR}/keys/private.pem" -pubout -out "${DEPLOY_DIR}/keys/public.pem"
    chmod 600 "${DEPLOY_DIR}/keys/private.pem"
    chmod 644 "${DEPLOY_DIR}/keys/public.pem"
else
    echo "[4/7] JWT keys already exist, skipping."
fi

# ── 5. Generate .env with secure passwords ───────────────────────────────────
if [ ! -f "${DEPLOY_DIR}/.env" ]; then
    echo "[5/7] Generating .env with secure passwords..."

    SECRET_KEY=$(openssl rand -hex 32)
    PASSWORD_PEPPER=$(openssl rand -hex 16)
    PG_PASSWORD=$(openssl rand -hex 24)
    REDIS_PASSWORD=$(openssl rand -hex 24)
    RABBITMQ_PASSWORD=$(openssl rand -hex 24)
    MINIO_PASSWORD=$(openssl rand -hex 24)
    PROMETHEUS_TOKEN=$(openssl rand -hex 24)

    cat > "${DEPLOY_DIR}/.env" <<ENVEOF
# ═══════════════════════════════════════════════════════
# DentalOS Production — Auto-generated by setup-server.sh
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ═══════════════════════════════════════════════════════

# ─── Docker Compose Services ─────────────────────────
POSTGRES_DB=dentalos
POSTGRES_USER=dentalos
POSTGRES_PASSWORD=${PG_PASSWORD}

REDIS_PASSWORD=${REDIS_PASSWORD}

RABBITMQ_USER=dentalos
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
RABBITMQ_VHOST=dentalos

MINIO_ROOT_USER=dentalos_minio
MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}

# ─── Application ─────────────────────────────────────
ENVIRONMENT=production
DEBUG=false
APP_NAME=DentalOS
APP_VERSION=1.0.0
LOG_LEVEL=WARNING
ALLOWED_HOSTS=${DOMAIN}

# ─── Server ──────────────────────────────────────────
HOST=0.0.0.0
PORT=8000
WEB_WORKERS=2

# ─── Security ────────────────────────────────────────
SECRET_KEY=${SECRET_KEY}
PASSWORD_PEPPER=${PASSWORD_PEPPER}

# ─── Database ────────────────────────────────────────
DATABASE_POOL_SIZE=10
DATABASE_MAX_OVERFLOW=20
DATABASE_ECHO=false

# ─── RabbitMQ ────────────────────────────────────────
SYNC_QUEUE=false

# ─── JWT (RS256) ─────────────────────────────────────
JWT_PRIVATE_KEY_PATH=keys/private.pem
JWT_PUBLIC_KEY_PATH=keys/public.pem
JWT_KEY_ID=dentalos-key-1
JWT_ALGORITHM=RS256
JWT_ISSUER=dentalos-api
JWT_AUDIENCE=dentalos-api
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=30
PASSWORD_BCRYPT_ROUNDS=12
LOCKOUT_THRESHOLD=5
LOCKOUT_DURATION_MINUTES=15
TENANT_SCHEMA_PREFIX=tn_

# ─── CORS ────────────────────────────────────────────
CORS_ORIGINS=https://${DOMAIN}
FRONTEND_URL=https://${DOMAIN}

# ─── File Storage (MinIO) ────────────────────────────
S3_ACCESS_KEY=dentalos_minio
S3_SECRET_KEY=${MINIO_PASSWORD}
S3_BUCKET_NAME=dentalos-prod
S3_REGION=us-east-1

# ─── AI (fill in your API keys) ─────────────────────
VOICE_STT_PROVIDER=openai
VOICE_NLP_PROVIDER=anthropic
OPENAI_API_KEY=CHANGE_ME
ANTHROPIC_API_KEY=CHANGE_ME
ANTHROPIC_MODEL=claude-haiku-4-5-20251001
ANTHROPIC_MODEL_TREATMENT=claude-sonnet-4-5-20250514

# ─── Email (fill in your SendGrid key) ───────────────
SENDGRID_API_KEY=CHANGE_ME
SENDGRID_FROM_EMAIL=noreply@dentalos.co
SENDGRID_FROM_NAME=DentalOS

# ─── Monitoring ──────────────────────────────────────
SENTRY_DSN=CHANGE_ME
SENTRY_TRACES_SAMPLE_RATE=0.1
SENTRY_ENVIRONMENT=production
PROMETHEUS_ENABLED=true
PROMETHEUS_TOKEN=${PROMETHEUS_TOKEN}
ENVEOF

    chmod 600 "${DEPLOY_DIR}/.env"
    echo "    .env written to ${DEPLOY_DIR}/.env"
    echo "    >>> IMPORTANT: Edit .env and fill in CHANGE_ME values (API keys, Sentry DSN)"
else
    echo "[5/7] .env already exists, skipping. Delete it to regenerate."
fi

# ── 6. Configure UFW firewall ────────────────────────────────────────────────
echo "[6/7] Configuring firewall (UFW)..."
if ! command -v ufw &>/dev/null; then
    apt-get install -y -qq ufw
fi
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp comment "SSH"
ufw allow 80/tcp comment "HTTP"
ufw allow 443/tcp comment "HTTPS"
ufw --force enable

# ── 7. Install & configure Nginx + certbot ───────────────────────────────────
echo "[7/7] Installing Nginx and certbot..."
apt-get install -y -qq nginx certbot python3-certbot-nginx

# Copy Nginx config if the source exists alongside this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NGINX_SRC="${SCRIPT_DIR}/../../nginx/dentalos.conf"
if [ -f "${NGINX_SRC}" ]; then
    cp "${NGINX_SRC}" /etc/nginx/sites-available/dentalos
    ln -sf /etc/nginx/sites-available/dentalos /etc/nginx/sites-enabled/
    rm -f /etc/nginx/sites-enabled/default
    # Create certbot webroot
    mkdir -p /var/www/certbot
    nginx -t && systemctl reload nginx
    echo "    Nginx configured. Run: sudo certbot --nginx -d ${DOMAIN}"
else
    echo "    Nginx config not found at ${NGINX_SRC} — copy manually from nginx/dentalos.conf"
fi

echo ""
echo "═══════════════════════════════════════════════════"
echo "  Setup complete!"
echo ""
echo "  Next steps:"
echo "    1. Edit ${DEPLOY_DIR}/.env — fill in CHANGE_ME values"
echo "    2. Copy JWT keys to backend/keys/ (or mount from ${DEPLOY_DIR}/keys/)"
echo "    3. Run: sudo certbot --nginx -d ${DOMAIN}"
echo "    4. Run: scripts/deploy/first-deploy.sh"
echo "═══════════════════════════════════════════════════"
