"""Voice clinical note model — lives in each tenant schema (AI-03).

Stores the SOAP-structured clinical note generated by Claude from
a voice dictation transcription. Linked to a VoiceSession with
context='evolution'.

Clinical data is NEVER hard-deleted (regulatory requirement).
"""

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import TenantBase, TimestampMixin, UUIDPrimaryKeyMixin


class VoiceClinicalNote(UUIDPrimaryKeyMixin, TimestampMixin, TenantBase):
    """A SOAP-structured clinical note from voice dictation.

    Status transitions:
      processing -> completed   (Claude finished structuring)
      processing -> failed      (Claude or parsing error)
      completed  -> saved       (doctor reviewed and saved as evolution note)
      completed  -> discarded   (doctor rejected the note)
    """

    __tablename__ = "voice_clinical_notes"
    __table_args__ = (
        CheckConstraint(
            "status IN ('processing', 'completed', 'failed', 'saved', 'discarded')",
            name="chk_voice_clinical_notes_status",
        ),
        Index("idx_voice_clinical_notes_session", "session_id"),
        Index("idx_voice_clinical_notes_patient", "patient_id"),
        Index("idx_voice_clinical_notes_doctor", "doctor_id"),
        Index("idx_voice_clinical_notes_created", "created_at"),
    )

    # Foreign keys
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("voice_sessions.id"),
        nullable=False,
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("patients.id"),
        nullable=False,
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=False,
    )

    # Input — raw transcription text
    input_text: Mapped[str] = mapped_column(Text, nullable=False)

    # SOAP structured note output (JSONB)
    structured_note: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        server_default=text("'{}'::jsonb"),
        default=dict,
    )

    # Auto-linked clinical codes
    linked_teeth: Mapped[list[int] | None] = mapped_column(
        ARRAY(Integer), nullable=True
    )
    linked_cie10_codes: Mapped[list] = mapped_column(
        JSONB,
        nullable=False,
        server_default=text("'[]'::jsonb"),
        default=list,
    )
    linked_cups_codes: Mapped[list] = mapped_column(
        JSONB,
        nullable=False,
        server_default=text("'[]'::jsonb"),
        default=list,
    )

    # Template integration (optional)
    template_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("evolution_templates.id"),
        nullable=True,
    )
    template_mapping: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # LLM metadata
    model_used: Mapped[str] = mapped_column(String(100), nullable=False)
    input_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    output_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Lifecycle
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="processing"
    )
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Review tracking
    reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    clinical_record_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )

    # Soft delete
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    def __repr__(self) -> str:
        return (
            f"<VoiceClinicalNote session={self.session_id} "
            f"patient={self.patient_id} status={self.status}>"
        )
